### PR TITLE
Mahdi Chowdhury - Assignment 0

### PR DESCRIPTION
**Pull request by mahdic**
Dear Dr. Price,
I encountered many problems with GitKraken and found myself having a difficult time pushing my changes and creating a pull request. At the last minute, I manually uploaded every file I edited within Atom to at the very least be able to make this pull request.

### CODE REVIEW

**Comment by titaniumbones** [comment]
Sorry you had this trouble.  You should find a way to make at least one more commit so that you can pass all the tests. I haven't looked closely at yr code yet but hopefully that will be the only issue. On Jan 15, 2018 8:28 PM, mahdic <notifications@github.com> wrote:Dear Dr. Price,
I encountered many problems with GitKraken and found myself having a difficult time pushing my changes and creating a pull request. At the last minute, I manually uploaded every file I edited within Atom to at the very least be able to make this pull request.



You can view, comment on, or merge this pull request online at:
  https://github.com/DigitalHistory/assignment-00-git-and-github/pull/25

Commit Summary
Add files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via upload

File Changes

    M
    Reflection/reflection-template.md
    (5)
  
    A
    images/mahdi_chowdhury.jpg
    (0)
  
    A
    students/35115677.json
    (15)
  

Patch Links:
https://github.com/DigitalHistory/assignment-00-git-and-github/pull/25.patchhttps://github.com/DigitalHistory/assignment-00-git-and-github/pull/25.diff

**Comment by titaniumbones** [comment]
Oops, never mind,. I see you made multiple commits. On Jan 15, 2018 8:35 PM, Matt Price <matt.price@utoronto.ca> wrote:Sorry you had this trouble.  You should find a way to make at least one more commit so that you can pass all the tests. I haven't looked closely at yr code yet but hopefully that will be the only issue. On Jan 15, 2018 8:28 PM, mahdic <notifications@github.com> wrote:Dear Dr. Price,
I encountered many problems with GitKraken and found myself having a difficult time pushing my changes and creating a pull request. At the last minute, I manually uploaded every file I edited within Atom to at the very least be able to make this pull request.



You can view, comment on, or merge this pull request online at:
  https://github.com/DigitalHistory/assignment-00-git-and-github/pull/25

Commit Summary
Add files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via uploadAdd files via upload

File Changes

    M
    Reflection/reflection-template.md
    (5)
  
    A
    images/mahdi_chowdhury.jpg
    (0)
  
    A
    students/35115677.json
    (15)
  

Patch Links:
https://github.com/DigitalHistory/assignment-00-git-and-github/pull/25.patchhttps://github.com/DigitalHistory/assignment-00-git-and-github/pull/25.diff

**Comment by titaniumbones** [comment]
looks good -- hopefully you can figure out the local tools for next time. Next time also please use more meaningful commit messages! But looks good overall.

**Comment by titaniumbones** [comment]
OK, actually @mahdic , there is in fact a problem with this PR. Instead of **adding** your reflection in a new fie called `Reflection/mahdic.md`, you **modified** `Reflection/reflection-template.md`. Can yo uplease fix this by 

a) copying your current reflection to a new file `Reflection/mahdic.md`. 
b) **restoring** the old version by copying the text from https://raw.githubusercontent.com/DigitalHistory/assignment-00-git-and-github/master/Reflection/reflection-template.md into the existing `Reflection/reflection-template.md`.
c) submitting a new PR

You need to make both changes, I'm afraid, or I won't be able to merge the change. 

Good luck!

mp

**Comment by mahdic** [comment]
Dear Dr. Price,

I have just made these changes and submitted a pull request. However, there is one thing to note:

I was unable to access the link to the old version – nor was I able to the original reflection-template.md on "assignment-00-git-and-github/master/Reflection." What I have uploaded instead, considering these limitations, is my mahdic.md reflection with all my answers removed so that the text is like the original file.

**Pull request merged**
