### PR TITLE
Add existing file

### PR DESCRIPTION
**Pull request by sanjum2801**

### CODE REVIEW

**Comment by titaniumbones** [comment]
can you pls remove ` students/.DS_Store` from the repo by executing `git rm -r --cached  students/.DS_Store`, then committing yr changes, then re-pushing? Thank you!

**Comment by sanjum2801** [comment]
I executed the command in terminal but when I tried to commit in atom I kept being told there was nothing to commit, and can't push anything. I tried again, and got the error: 
screen shot 2018-01-16 at 10 57 37 pm


If it helps, I checked if students/.DS_Store was locally stored using `ls` on terminal on `assignment-00-git-and-github/students` and it did not show, but it still shows in atom. Also, before I directly edited on  `utils/allstudents.js` to add the image and committed those changes there were no conflicts. I didn't check for conflicts after that, so possibly something went wrong there?

**Comment by titaniumbones** [comment]
Writing from my phone so it's a little hard for me to type commands and check things, but:On Jan 16, 2018 11:01 PM, sanjum2801 <notifications@github.com> wrote:I executed the command in terminal but when I tried to commit in atom I kept being told there was nothing to commit, and can't push anything. I tried again, and got the error:

I may have typed this wrong, you need to precede the RM by git - you want to remove the file from the repository without actually deleting it.  If it helps, I checked if students/.DS_Store was locally stored using ls on terminal on assignment-00-git-and-github/students and it did not show, but it still shows in atom.restore won't show up with a regular ls command, you need ls -a to show hidden files.  But don't worry about this actually.. Also, before I directly edited on  utils/allstudents.js to add the image and committed those changes there were no conflicts. I didn't check for conflicts after that, so possibly something went wrong there?Not sure.  The main thing is that got doesn't let me edit the file in the web interface do it's a pain to manage the merge. If you want you can just git rm -r --cached utils/allstudents.jsonThst should fix the conflict. Be sure to commit all your changes before pushing! And then take a look at the conflicts, if one still remains, let me know.

**Comment by sanjum2801** [comment]
Every time I execute the command 'git rm -r --cached students/.DS_Store', I get the response 'rm 'students/.DS_Store' and similarly when I executed 'git rm -r --cached utils/allstudents.js'.

But when I go to atom, it won't let me commit most of the time, and the 1 commit I managed to make didn't resolve the conflict. When I go to atom, the file and the folder are yellow indicating changes, but if I then say to "add and commit" I'm told the file/folder is added, and there's nothing to commit. If I save first and then try again, sometimes the same thing happens, other times the yellow disappears. If, after executing the command, I save immediately on atom and then try to commit, again I either have the nothing to commit message or the yellow disappears. I've tried doing it on the file and on the folder.

**Comment by titaniumbones** [comment]
not sure what's going on, I'll do a manual fix here, but please come see me after class/during office hours to be sure you're using git right (will be necessary later on)

**Pull request merged**
