### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by rosalinddeibert**

### CODE REVIEW

**Comment by titaniumbones** [comment]
Hi @rosalinddeibert , your material looks good but I can't merge this until you remove your `.DS_Store` file with `git rem -r --cached .DS_Store` (at the command line; then commit & push, and you should be good to go. Thanks!

**Comment by rosalinddeibert** [comment]
Hi @titaniumbones , I think I've done it now, is it working?

**Comment by titaniumbones** [comment]
Still looks a little wonky -- take a look at the changed files view:
https://github.com/DigitalHistory/assignment-00-git-and-github/pull/22/files
. Looks like `Reflection/reflection-template.md` was also deleted by
accident. Can you restore it to its original condition by adding a new
file with the old contents, then pushing again? thank you!

**Comment by rosalinddeibert** [comment]
Hi @titaniumbones 

Is this correct now? 

Thanks!

Rosalind

**Comment by titaniumbones** [comment]
yes, now is good!

**Pull request merged**
